main: lineTest.cpp Rasterizer.cpp Rasterizer.h simpleCanvas.cpp simpleCanvas.h
	g++ -c lineTest.cpp Rasterizer.cpp simpleCanvas.cpp
	g++ -o lineTest lineTest.o Rasterizer.o simpleCanvas.o -lsfml-graphics -lsfml-window -lsfml-system
